### ISSUE TITLE
exemple gstreamer receiving pipeline

### ISSUE THREAD

**Issue by ghost** [Consti10/LiveVideoStreamProducer#1]
I tried to decode the stream with:
`gst-launch-1.0 udpsrc port=5600 ! "application/x-rtp, payload=127" ! rtph264depay ! decodebin ! glimagesink`
But I got this error:
```
Received invalid RTP payload, dropping
WARNING: from element /GstPipeline:pipeline0/GstRtpH264Depay:rtph264depay0: Could not decode stream.
```
Is it possible to use gstreamer to decode the stream?

**Comment by Consti10** [comment]
Hello,
Can you try again with this app ?
https://github.com/consti10/livevideo10ms

I did a lot of changes to the producer and merged it into my video example app.
STARTSSTREAMINGSERVER and SS_SETTINGS are the buttons.
Select 'rtp' as video transmitter stream mode andreceiving should work with gstreamer.

**Comment by Consti10** [comment]
You can use the same app as receiver, too (if you have 2 android phones)

**Comment by Consti10** [comment]
I am testing gstreamer and the Example app right now.
Using this pipeline you can make sure data is received:
gst-launch-1.0 udpsrc port=5600 -v ! fakesink dump=1

But rtp doesn't work yet for some resaon ... ?

**Comment by Consti10** [comment]
So rtp doesn't work right now. ( only receiving rtp using the example app)
However, raw does work with the example app.
Gstreamer pipeline:
gst-launch-1.0 udpsrc port=5600 ! h264parse ! decodebin ! autovideosink

SS_Settings: VIDEO_TRANSMITTER_STREAM_MODE: RAW H264

**Comment by Consti10** [comment]
I am not quite sure why rtp doesn't work with gstreamer.
It works fine withe the example and FPV_VR app

**Comment by Consti10** [comment]
So there must be something special inside the rtp packets that gstreamer needs to decode the stream. If you can figure out what, please let me know.
In the meantime, raw is working also inside gstreamer and rtp works with the FPV_VR app, so I won't do any more debugging right now (I'l keep it in the back of my head though, if I can find out what's wrong I'l let you know)

**Comment by Consti10** [comment]
Going to archieve this repo.
See https://github.com/Consti10/LiveVideo10ms/issues/3
